export { default as Background } from './Background';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
export { default as Hero } from './Hero';
export { default as Main } from './MainContent';
export { default as Navbar } from './Navbar';
export { default as ProjectCard } from './ProjectCard';
export { default as Projects } from './Projects';
export { default as CV } from './CV';
